version: '3.9'

services:
  postgres:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 1
    command: ['start-dev']
    ports:
      - '3333:8080'
